apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.mcpserver.fullname" . }}
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
    component: mcp-server
spec:
  type: {{ index .Values "mcp-server" "service" "type" }}
  ports:
    - port: {{ index .Values "mcp-server" "service" "port" }}
      targetPort: {{ index .Values "mcp-server" "service" "targetPort" }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo-chatbot.selectorLabels" . | nindent 4 }}
    component: mcp-server
  sessionAffinity: None
